changeLogFile=changelog/db.changelog-master.yaml
url=jdbc:postgresql://localhost:5432/awesome-database
username=
password=
driver=org.postgresql.Driver
liquibaseSchemaName=public
outputChangeLogFile=changelog/db.changelog-generated.yaml
