// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"awesomeProject/config"
	"awesomeProject/internal/api"
	"awesomeProject/internal/api/controller"
	"awesomeProject/internal/appcontext/database/postgres"
	"awesomeProject/internal/repository"
	"awesomeProject/internal/service"
)

// Injectors from wire_api.go:

func InitializeAccountAPI() *api.AccountAPI {
	app := controller.NewFiberApp()
	accountService := InitializeAccountService()
	accountAPI := api.NewAccountAPI(app, accountService)
	return accountAPI
}

func InitializeTransferAPI() *api.TransferAPI {
	app := controller.NewFiberApp()
	transferService := InitializeTransferService()
	accountService := InitializeAccountService()
	transferAPI := api.NewTransferAPI(app, transferService, accountService)
	return transferAPI
}

// Injectors from wire_controller.go:

func InitializeController() *controller.Controller {
	app := controller.NewFiberApp()
	accountAPI := InitializeAccountAPI()
	transferAPI := InitializeTransferAPI()
	configuration := config.Load()
	controllerController := controller.NewController(app, accountAPI, transferAPI, configuration)
	return controllerController
}

// Injectors from wire_repo.go:

func InitializeAccountRepo() *repository.AccountRepo {
	db := postgres.GetDB()
	accountRepo := repository.NewAccountRepo(db)
	return accountRepo
}

func InitializeTransferRepo() *repository.TransferRepo {
	db := postgres.GetDB()
	transferRepo := repository.NewTransferRepo(db)
	return transferRepo
}

func InitializeAuditLogRepo() *repository.AuditLogRepo {
	db := postgres.GetDB()
	auditLogRepo := repository.NewAuditLogRepo(db)
	return auditLogRepo
}

// Injectors from wire_service.go:

func InitializeAccountService() *service.AccountService {
	accountRepo := InitializeAccountRepo()
	transferRepo := InitializeTransferRepo()
	auditLogRepo := InitializeAuditLogRepo()
	accountService := service.NewAccountService(accountRepo, transferRepo, auditLogRepo)
	return accountService
}

func InitializeTransferService() *service.TransferService {
	accountRepo := InitializeAccountRepo()
	transferRepo := InitializeTransferRepo()
	auditLogRepo := InitializeAuditLogRepo()
	transferService := service.NewTransferService(accountRepo, transferRepo, auditLogRepo)
	return transferService
}
